fixed docs section padding
layer5io/getnighthawk pull request #121
Opened 2021-05-29 12:57 UTC by NikhilSharma03

Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
- There was an issue with section padding on the docs page.

## Before
![Old](https://user-images.githubusercontent.com/58226527/120071098-4a189e00-c0ab-11eb-9abd-7db5af930357.png)

- Added padding around the links

## After Changes
![New](https://user-images.githubusercontent.com/58226527/120071113-53096f80-c0ab-11eb-84e8-96e8c4b3a833.png)

**Notes for Reviewers**
Let me know if we can make any other changes. Thank you.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-05-30 15:21 UTC, vinayaksh42 commented on docs/pages/docs.html
> +                  <div id="flush-collapse{{docs.number}}" class="accordion-collapse collapse" style="padding: 15px;" aria-labelledby="flush-heading{{docs.number}}" data-bs-parent="#accordionFlushExam
```suggestion
                  <div id="flush-collapse{{docs.number}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{docs.number}}" data-bs-parent="#accordionFlushExample">
```

2021-05-30 15:23 UTC, vinayaksh42 requested changes

2021-05-30 15:23 UTC, vinayaksh42 commented on docs/pages/docs.html
> +                  <div id="flush-collapse{{docs.number}}" class="accordion-collapse collapse" style="padding: 15px;" aria-labelledby="flush-heading{{docs.number}}" data-bs-parent="#accordionFlushExam
avoid using inline styling as it gets a little difficult to track various different CSS changes. Instead, do all the styling changes in the designated folder.

2021-05-30 16:17 UTC, leecalcote commented
Ignoring issue of inline style, the effect is certainly an improvement. Nice work, @NikhilSharma03.

2021-05-31 12:20 UTC, NikhilSharma03 commented
Thank you @leecalcote and @vinayaksh42 .Can you please review the changes?

2021-05-31 17:53 UTC, JubayerJoy approved these changes
LGTM 🚀

2021-05-31 20:47 UTC, vinayaksh42 commented
Great work! @NikhilSharma03

2021-05-31 20:48 UTC, vinayaksh42 approved these changes

2021-05-31 20:48 UTC, merged

2021-06-01 11:58 UTC, NikhilSharma03 commented
Thank you @vinayaksh42