[Site] Updated docs section style
layer5io/getnighthawk pull request #128
Opened 2021-06-03 12:30 UTC by NikhilSharma03

Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
Updated style and color of docs section.

## After Changes
![Screenshot from 2021-06-03 17-55-52](https://user-images.githubusercontent.com/58226527/120644781-56c73880-c495-11eb-81ab-cced7c9b2764.png)

This PR fixes #124 

**Notes for Reviewers**
Let me know if there are any other changes or fixes we can make.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-06-03 12:31 UTC, NikhilSharma03 commented
@vinayaksh42 @JubayerJoy Can you please review the changes? Thank you.

2021-06-03 13:25 UTC, JubayerJoy reviewed
@NikhilSharma03 really nice work! 🚀
Some suggestions,
1. The menu is not closing on click, please change it so it collapses on click.
2.  Keeping the first menu item open by default would look nicer and give good UX.

2021-06-04 06:37 UTC, Anita-ihuman commented
> 1. The menu is not closing on click, please change it so it collapses on click.

well, I think keeping the dropdown closed is better tho. This is because by the time the details, expected to be on the doc page are complete, the page would look too busy having the dropdown open by default.

2021-06-04 06:40 UTC, Anita-ihuman reviewed
Thank you for taking this up.
 it would be great if the dropdown closes back on clicking the button.
right now it just Opens.

2021-06-04 11:12 UTC, leecalcote commented
@NikhilSharma03, are you trying to tell the user that "there's no going back"? ;)

2021-06-04 11:17 UTC, NikhilSharma03 commented
@Anita-ihuman @JubayerJoy 
Changes to make :
- Dropdown closes back on clicking the button
- Keeping the dropdown closed
Can you please confirm the changes so I can work on them. Thank you.

2021-06-04 11:21 UTC, Anita-ihuman commented
> @Anita-ihuman @JubayerJoy
> Changes to make :
> 
> * Dropdown closes back on clicking the button
> * Keeping the dropdown closed
> 
> Can you please confirm the changes? Thank you.

Yes, Those are the changes to be made.

2021-06-04 14:36 UTC, NikhilSharma03 commented
@Anita-ihuman @JubayerJoy Can you please review the changes.

2021-06-04 15:07 UTC, vinayaksh42 requested changes

2021-06-04 15:07 UTC, vinayaksh42 commented on docs/_sass/getnighthawk.scss
> +.sidebar  {
Removal of this empty class.

2021-06-04 15:42 UTC, NikhilSharma03 commented on docs/_sass/getnighthawk.scss
> +.sidebar  {
Yeah Sure.

2021-06-04 15:47 UTC, vinayaksh42 approved these changes
Great work @NikhilSharma03

2021-06-04 16:06 UTC, Anita-ihuman approved these changes
Looks good to me

2021-06-04 16:29 UTC, JubayerJoy approved these changes
Really Nice work @NikhilSharma03 🚀
LGTM 🎈

2021-06-05 08:20 UTC, merged