Add support to unmarshal json in cli option struct
layer5io/getnighthawk pull request #321
Opened 2023-07-23 22:50 UTC by abdullah1308

**Description**

This PR fixes #

**Notes for Reviewers**

Dependabot updates also addressed

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-25 15:25 UTC, MUzairS15 requested changes
@

2023-07-25 15:25 UTC, MUzairS15 commented on pkg/proto/utils.go
> +	o := &struct {
@abdullah1308 The struct defined here is exactly same as https://github.com/layer5io/getnighthawk/blob/6c1b9423282d2f3fd81e214fe2c5a72c3ba183eb/pkg/proto/options.pb.go#L882 (also json tags are same), so why it is required to redefine?

2023-07-25 20:44 UTC, abdullah1308 commented on pkg/proto/utils.go
> +	o := &struct {
We've had this conversation on slack before, we cannot unmarshall json into the struct `CommandLineOptions` as the fields are of _custom types_ and not _Golang primitive types_.

Example error when trying to unmarshal the following json
```
{
    "requests_per_second": 3
}
```
```
ERRO[2023-07-19T23:43:26+05:30] json: cannot unmarshal number into Go struct field CommandLineOptions.requests_per_second of type wrapperspb.UInt32Value  app=meshery code=2208 probable-cause="Load test endpoint could be not reachable" severity=2 short-description="load test error: .unable to perform" suggested-remediation="Make sure load test endpoint is reachable"
```

The struct expects a value of type `wrapperspb.UInt32Value` for the field `RequestsPerSecond`.

2023-07-25 20:47 UTC, abdullah1308 commented on pkg/proto/utils.go
> +	o := &struct {
The structs aren't exactly the same. I've redefined the struct fields as primitives -

<img width="597" alt="image" src="https://github.com/layer5io/getnighthawk/assets/76054921/db91f337-2358-428a-9c2d-a6c4a1fdb6f8">

Then I assign value to the `CommandLineOptions` struct with the proper type -

<img width="510" alt="image" src="https://github.com/layer5io/getnighthawk/assets/76054921/aa97efc2-62e7-456d-94fe-8a379ad006cf">

2023-07-26 03:32 UTC, MUzairS15 approved these changes

2023-07-26 03:32 UTC, MUzairS15 commented on pkg/proto/utils.go
> +	o := &struct {
My bad, It didn’t came to my mind unless I saw that struct carefully that it has non golang primitives.

2023-07-26 03:32 UTC, MUzairS15 commented
@abdullah1308 some lint checks to address?

2023-07-26 10:44 UTC, merged