Added Card Component & fixed missing logo in footer
layer5io/getnighthawk pull request #60
Opened 2021-02-21 19:44 UTC by chinmaym07

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #40 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-02-21 20:26 UTC, vinayaksh42 requested changes

2021-02-21 20:26 UTC, vinayaksh42 commented on docs/_sass/getnighthawk.scss
> +        border-bottom: 0.3rem solid $saffron;
change `0.3rem` to `0.4rem`

2021-02-21 20:26 UTC, vinayaksh42 commented on docs/_sass/getnighthawk.scss
> +                font-weight: bolder;
Increase the font-weight to `900`

2021-02-21 20:26 UTC, vinayaksh42 commented on docs/_sass/getnighthawk.scss
> +    .card-item:hover:after {
add another case separately for .card-item:hover, which should include the increased box-shadow.

2021-02-21 20:26 UTC, vinayaksh42 commented on docs/_sass/getnighthawk.scss
> +        box-shadow:0 2px 10px rgba(0,0,0,0.4);
Decrease the `box-shadow` to bare minimum
![chrome_rNGOhrTFG6](https://user-images.githubusercontent.com/54861487/108637529-0fea9f80-74b1-11eb-86a6-384ff9672d58.png)

2021-02-21 20:26 UTC, vinayaksh42 commented
Initially the card should have a very faint shadow and upon hovering it should increase, also increase the height of the yellow line by 2 times.
![chrome_JhAqzdfG6f](https://user-images.githubusercontent.com/54861487/108637178-88e8f780-74af-11eb-9851-4f3aee16a94b.png)

2021-02-21 20:38 UTC, leecalcote commented on docs/_sass/getnighthawk.scss
> +                font-weight: bolder;
```suggestion
                font-weight: 900;

```

2021-02-21 20:38 UTC, leecalcote commented on docs/_sass/getnighthawk.scss
> +        border-bottom: 0.3rem solid $saffron;
```suggestion
        border-bottom: 0.4rem solid $saffron;

```

2021-02-22 01:30 UTC, leecalcote commented
Nice!

2021-02-22 19:08 UTC, vinayaksh42 approved these changes
Looks great now!

2021-02-23 14:16 UTC, leecalcote approved these changes

2021-02-23 14:17 UTC, merged